language: node_js
node_js:
- 9

script:
- yarn build

deploy:
  provider: s3
  access_key_id: AKIAJAENHOEXN33QLWNA
  secret_access_key:
    secure: QZ6wbWy23jhCwAdJkv5NwtZGAlB/+xACF7SuezumpU9h+RFiWwkUVZmRfZ5vZ4P5TXjlVhk2Ifww8kgPsRXVm8CjOUPY4KGIvQu/QWS3rBtKGHCmZFZEGJbr3xi6uDIKiW44T/2qPf3rlFgbgTj8i/rWWlhghTPWcVtAZrTsVzGq+2w2rJ/pfOM89pZGr1Wutl0K/dlb2BUScqS7gfreLwiyharkNbMfLR4xoe9SP7KRH/Aw8THFwODxsKRy0DsdvN7I8N5v5M0jScDDCqKLgccU4bPPWuMgCxW07rpCaDYiVDVNKgWu1f3B72sSCJ1LisEZzO2CSR32Sp6YPfgscsgkR0T0B/2W+NxjBh1pMGhCYyXmv+Pon9wBXlVYlVhDJe283tkO5ZmLCd09YNQVg1r3ezOnMVsaUvnPN+2yAa7klQiIIWiyTB3VjevH0M0nKVF2BnQ0Fq1gkeNK492SuHxnjgOWa7F6ovv27iWZpb5807f1yQrpjdZLb+XfaNwgRDpkT6RzShgHzln8uuXJZjqS55UAYMomNm3AMmxD2KyN0KXPYSb/px2cGITbHbXCbG3pKUvAMW9MGyn4/OqupFYkkpcncbeEs4azfPlA2o9HSr79jgVG6zpmCJdNi1PDHkHBYkoecZayYIGcaKogvi79dW/CBrD1317EoNVTjc0=
  bucket: humans-tcr
  local_dir: build
  acl: public_read
  skip_cleanup: true
  on:
    repo: humansTCR/tcr-ui
    branch: master
