language: node_js
node_js:
  - 9

script:
  - yarn build

deploy:
  provider: s3
  access_key_id:
    secure: "IS+mGKMxmqZ5w8o8R4eFnJewcOvdJ7wJmFO3C2PZ4lqKLaj9fiiE3o6ZTp0C4J9lbzSk5xCqu8rrfKLXy7Zbh9XrC2N+NLpv/FuOQyeznLVEpw1AdGcxLckqA3zOr040A+bIUMTJ29uZrhLpROn76QtvaRurA1gvmN/S750jTQwTBd/HBvOXyaE99pgOyUtX9Z1EgmGhKXlPuBcioCF7UmNZCNzKxqRUZTOZj9eZZZUxuW6hhgSthCDJJHoXl/LS+WC7al1613o+G3tfr3R4JLkNUWrpbSOGNC88iHbsvwQrC3AuqFlpl9AZqYMzzB667AYdkujDT9yOf2Bq7GUkY4UufzLPwwycc68ekNs+2gFErYlxaSVmfe0swAjTbcPSxb/fOc7lVU8r2U2IoWo0OtOsCWuAzJBjES+NSowG+VJ2bn0GQhQ9jlarP1xLIdoJfXZmqZ2YE99cncuuUWE/edUWp1lY3khKVkF5S/tTAdz9BOcfGw3hzzBcidz7vbsJrQqAopYFOjO2ivU5RG0DB+l5+tzbmsw15uJr8kUAoaQ7COgHDJLVwUZeKW0O8qxrEJtwiRvIyH1RhNdsHer1RKWr9jSu3QC66+asgbHhfNI5yGat7MgcTG22ashpCIpmo1dUCffhoT5+BEJelRMmXxPmFxLFSk3VhdfDFZpizEA="
  secret_access_key:
    secure: "nVmZanJY8JUi6a8OuYFJ83LxqJdj1YOlreRh66HRqCuj8NZSygFUW05GpE+vhOypwYr6eK4STXKDJOgMlT1DwvILOg/uJv/XOHJe4F8Pxar0TahSmAK8yt+gClQmkYpc2r2i9NuZk4MW2bTGE0zNGWzahb8CTlsh9KN3gSDhR8gvrF2ASIJj3PLRJn/7fPs24wBfs67auZDbiv4d2FIm9l3PYB2izy07YYcsEbW21jS1Ti6hTc9KLvahikIuwolzveARe8tHjV24+WJxg+HMjbXRvyBX5E5oSFOLS4/ne5HF8YwGi9mTSEs1OdXAu744vQn+iIaeiGd7WnXitmw7tkjoZxe98xIlyNjA9sKe4CCba9J2a5f4bmpcuJusrJg4L7R0AtOc82PjK1Qk0JkjUNTNrIOfXiVNQWGKYaofvZgZ2/uZSJxpi/el2VQLQwsb+12qQa99DAJkSwfK0cLlubGbw6T6b5lp1YmVGvDud5cskA+cP6D6bVSMWAmrOfi9+pRHac3/pvQS9REfiSdkWUm3TZpcr6e/sn81ownWuSeOq8q4QzDQtfUARyZzyXkUs1wDAYnRUHSI97zgV116mtZi+j+70UMAtr4QlZ+KPmQwb9MYmmBeo8dvLzz6wmQMflG+EAn0hU05/RipcQ1okUQQ97DS7qawZGoXi4IFbtQ="
  bucket: humans-tcr
  region: eu-central-1
  local_dir: build
  skip_cleanup: true
  on:
    branch: master
